name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Configure
        run: cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure